### ISSUE TITLE
adrgen ported to Windows ?

### ISSUE THREAD

**Issue by frederic-baucher** [asiermarques/adrgen#8]
Hi,

adrgen looks great. I use it on Linux but some of the machine where I need it are under Windows.
I am quite new to GO. Do you think that porting adrgen to Windows platform could be tricky ?

Thx, Fred.

**Comment by madhon** [comment]
Ive compiled and used it on windows with no real issues so far

**Comment by asiermarques** [comment]
I will port to node the tool in the following weeks. Despite it will be not "officially" supported, I will do my best to ensure the best compatibility.
